### ISSUE TITLE
New Interfaces structure

### ISSUE THREAD

**Issue by codeflight1** [jboullion/rad-toolkit#1]
Properly parse and filter the new interfaces property structure.

Example:
```js
properties: [
  {
    property: "",
    quantity: 1
  },
  ...
]
```

**Comment by jboullion** [comment]
[Commit](https://github.com/jboullion/rad-toolkit/commit/a7b9826aad33812072d2f80ba6130e4e156ff94e)

**Comment by codeflight1** [comment]
Looks pretty good!

There does seem to be a small bug where items with an empty properties field fail to reappear when deselecting all filters.

**Comment by jboullion** [comment]
[Commit](https://github.com/jboullion/rad-toolkit/commit/3fa7af233af6072c7b1009818e3c3d5bcecae3dc)

**Comment by codeflight1** [comment]
LGTM
