### ISSUE TITLE
Add fields for new categories

### ISSUE THREAD

**Issue by codeflight1** [jboullion/rad-toolkit#14]
# Voltage Regulation
- output_voltage
- output_current
 
# FPGAs
- logic_cells
- io_count
 
# SBCs
- form_factor
- processor
- interfaces
- nv_memory_capacity
- volatile_memory_capacity
 
# Interface ICs
- primary_interface
- secondary_interfaces

**Comment by jboullion** [comment]
[Commit](https://github.com/jboullion/rad-toolkit/commit/7a7634478b3687d257c939d1131053b96d497840)

**Comment by codeflight1** [comment]
Seems pretty good, but secondary interfaces are not showing up.

**Comment by jboullion** [comment]
[Commit](https://github.com/jboullion/rad-toolkit/commit/4e8a8b8d13ba0e3b3a39bfe4598f3a585cc5cddd)

**Comment by codeflight1** [comment]
LGTM
