### ISSUE TITLE
Feature Request: Complex search and advanced category selection

### ISSUE THREAD

**Issue by codeflight1** [jboullion/rad-toolkit#17]
The current category selection is slightly cumbersome and will only get more so as categories are added. A better system I think is to show a home page with a list of parent categories that, when clicked, reveal a list of subcategories that can then be selected.

In addition to this, if one doesn't know what category a part would be in it is helpful to have a text search that searches all categories and then returns a list of categories with parts containing the search string.

Both of these features can be part of a splash screen of sorts, that greets the user and provides a more streamlined UX.

**Comment by jboullion** [comment]
Sorry I haven't responded to this!

I agree the current filtering isn't great. Definitely open to a different approach.

Could you create a wireframe of what you are describing? That helps me to understand the scope of the changes.

**Comment by codeflight1** [comment]
Sorry for the long delay, this is my basic idea for a home page. The search would then go to a similar categories page including only categories with parts containing the search string. I'll work on the about text, let me know if you have any more questions.
![Rad Toolkit Wireframe](https://github.com/jboullion/rad-toolkit/assets/17892997/a608dae0-be8b-49fe-b256-b03c9a223bd6)
