### ISSUE TITLE
Database type and component limits

### ISSUE THREAD

**Issue by jboullion** [jboullion/rad-toolkit#18]
I believe "fo**r**ward_voltage" and "fo**r**ward_current" are spelled "foward_current" and "foward_current" in DB.

I updated the max return from 50 to 200. Could also just list everything no matter how many, but that can sometimes lead to problems. The other option is to implement pagination, which we can do, but would rather not. Hopefully 200 is good enough for now. More than that and they will probably want / need to be filtering anyway :)

I updated the suffix for the three new properties. I have no idea what those words mean so let me know if the suffixes are incorrect.

**Comment by codeflight1** [comment]
That's correct, I have fixed the naming.

The suffixes are almost correct, but the values are being compressed down into integers. We need to properly handle things such as millivolts and milliamps, similar to the memory sizes.

**Comment by jboullion** [comment]
Updated suffix! [Commit](https://github.com/jboullion/rad-toolkit/commit/2eb744ef94c4eb6a40cc37f1bc59f9845411d8db)

**Comment by codeflight1** [comment]
LGTM
