### ISSUE TITLE
Hide voltage column for transistors

### ISSUE THREAD

**Issue by codeflight1** [jboullion/rad-toolkit#20]
There are specific columns for transistor voltages.

**Comment by jboullion** [comment]
Commit https://github.com/jboullion/rad-toolkit/commit/96393c215a6d7ddda8164d8e48779558613a5e65

**Comment by codeflight1** [comment]
LGTM

Could you also hide it for the diodes category?

**Comment by jboullion** [comment]
Commit https://github.com/jboullion/rad-toolkit/commit/9756e8bcbc5936bce140f32ea43bde4a048266de
