### ISSUE TITLE
Files field

### ISSUE THREAD

**Issue by codeflight1** [jboullion/rad-toolkit#3]
Add a new field to display the contents of the `files` table. This contains supplementary data such as test reports.

**Comment by jboullion** [comment]
I noticed the files only have a url. Will there be a name or other info to show? Or should we just show the urls?

**Comment by codeflight1** [comment]
It may be possible to add a name, as putting in all the URLs could be quite long. For now could you try displaying only the last part (e.g. file name) and I'll think about adding names later.

**Comment by jboullion** [comment]
[Commit](https://github.com/jboullion/rad-toolkit/commit/3ada3cbf42d9c3cacf717ca1b06f77e1c24b2dd9)

**Comment by codeflight1** [comment]
When multiple entries are available they run into each other, could you add a separator?

**Comment by jboullion** [comment]
[Commit](https://github.com/jboullion/rad-toolkit/commit/27ea2bc295ea97f0d3d84dcba1ed963cb166c857)

**Comment by codeflight1** [comment]
Perfect!
