### ISSUE TITLE
Fix contents of filter lists

### ISSUE THREAD

**Issue by codeflight1** [jboullion/rad-toolkit#4]
When changing to a new category the options from products in the previous category stay in the filter options.

**Comment by jboullion** [comment]
@codeflight1 I was unable to reproduce this. Could you tell me the path you are taking to reproduce?

**Comment by codeflight1** [comment]
1. Enter the FPGAs category, the package dropdown contains CQFP172 and CQFP84.
2. Move to the Interface ICs category (without refreshing the page), the dropdown will now contain CCGA296, CCGA360, etc. in addition to CQFP172 and CQFP84, which do not appear on any products in the new category.

**Comment by jboullion** [comment]
OK I was looking at the wrong thing, thanks! 

[Commit ](https://github.com/jboullion/rad-toolkit/commit/f198dbe02478b77297cc1e563c1a692122c5f890)
