### ISSUE TITLE
Store category + filters in URL

### ISSUE THREAD

**Issue by codeflight1** [jboullion/rad-toolkit#7]
This will allow keeping filtered results over page refreshes and sharing result links.

**Comment by jboullion** [comment]
I setup a basic url query string feature, but it definitely needs more testing.

[Commit](https://github.com/jboullion/rad-toolkit/commit/cc8dd5e66a4103538ee8da6e98d4d260b06cd237)

**Comment by codeflight1** [comment]
That looks great!

I'm not sure if this is related, but I'm now getting multiple options for the same value in the filter lists.

**Comment by jboullion** [comment]
@codeflight1 good catch, it probably is related. I'll sort it out!

**Comment by codeflight1** [comment]
Also probably related, filters now no longer work. The URL updates but the table does not.

**Comment by codeflight1** [comment]
Fixed in [commit](https://github.com/jboullion/rad-toolkit/commit/1343c2884fabc6203fd0ee71b522c58c443c4f9b)
