### ISSUE TITLE
Arrays show as string in details dialog

### ISSUE THREAD

**Issue by codeflight1** [jboullion/rad-toolkit#8]

**Comment by jboullion** [comment]
[Commit](https://github.com/jboullion/rad-toolkit/commit/a66774815ea26a149979aee27903f9c21c61a690)

**Comment by codeflight1** [comment]
Looks fixed, but the name, part number, and manufacturer no longer appear.

**Comment by jboullion** [comment]
Whoops! [Commit](https://github.com/jboullion/rad-toolkit/commit/5e4495fbf6f2825e7c03d43cebd9c69d81d27f76)

**Comment by codeflight1** [comment]
LGTM
